import java.util.HashMap;
public class Translator {
    private HashMap<Character, String> morse = new HashMap<>() {{
        put('A', "*-");
        put('B', "-***");
        put('C', "-*-*");
        put('D', "-**");
        put('E', "*");
        put('F', "**-*");
        put('G', "--*");
        put('H', "****");
        put('I', "**");
        put('J', "*---");
        put('K', "-*-");
        put('L', "*-**");
        put('M', "--");
        put('N', "-*");
        put('O', "---");
        put('P', "*--*");
        put('Q', "--*-");
        put('R', "*-*");
        put('S', "***");
        put('T', "-");
        put('U', "**-");
        put('V', "***-");
        put('W', "*--");
        put('X', "-**-");
        put('Y', "-*--");
        put('Z', "--**");
        put('1', "*----");
        put('2', "**---");
        put('3', "***--");
        put('4', "****-");
        put('5', "*****");
        put('6', "-****");
        put('7', "--***");
        put('8', "---**");
        put('9', "----*");
        put('0', "-----");
        put('.', "*-*-*-");
        put(',', "--**--");
        put('?', "**--**");
    }};
    private HashMap<String, Character> english = new HashMap<>() {{
        put("*-", 'A');
        put("-***", 'B');
        put("-*-*", 'C');
        put("-**", 'D');
        put("*", 'E');
        put("**-*", 'F');
        put("--*", 'G');
        put("****", 'H');
        put("**", 'I');
        put("*---", 'J');
        put("-*-", 'K');
        put("*-**", 'L');
        put("--", 'M');
        put("-*", 'N');
        put("---", 'O');
        put("*--*", 'P');
        put("--*-", 'Q');
        put("*-*", 'R');
        put("***", 'S');
        put("-", 'T');
        put("**-", 'U');
        put("***-", 'V');
        put("*--", 'W');
        put("-**-", 'X');
        put("-*--", 'Y');
        put("--**", 'Z');
        put("*----", '1');
        put("**---", '2');
        put("***--", '3');
        put("****-", '4');
        put("*****", '5');
        put("-****", '6');
        put("--***", '7');
        put("---**", '8');
        put("----*", '9');
        put("-----", '0');
        put("*-*-*-", '.');
        put("--**--", ',');
        put("**--**", '?');
    }};
    public String toMorse(char a) {
        return morse.get(a);
    }
    public char toEnglish(String s) {
        return english.get(s);
    }
}